# Generated by Django 5.2.13 on 2026-04-17 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vision_app', '0002_chatsession_image_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='AnalyzerCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_hash', models.CharField(db_index=True, max_length=128)),
                ('image_hash', models.CharField(db_index=True, max_length=128)),
                ('component', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('result_json', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('pdf_hash', 'image_hash')},
            },
        ),
        migrations.CreateModel(
            name='VisualDiffCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img1_hash', models.CharField(db_index=True, max_length=128)),
                ('img2_hash', models.CharField(db_index=True, max_length=128)),
                ('result_json', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['img1_hash', 'img2_hash'], name='vision_app__img1_ha_319f2f_idx')],
            },
        ),
    ]
